name: Deploy Static to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install and Build
        run: |
          npm ci
          npm run build
          mkdir -p dist-pages
          cp -r public/* dist-pages/ 2>/dev/null || true
          echo '<!DOCTYPE html>
          <html>
          <head>
            <meta charset="UTF-8">
            <title>ACCamargo - Plataforma Oncológica</title>
            <script src="https://cdn.tailwindcss.com"></script>
            <link href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.4.0/css/all.min.css" rel="stylesheet">
          </head>
          <body class="min-h-screen bg-gradient-to-br from-gray-50 via-green-50/30 to-emerald-50/20 flex items-center justify-center">
            <div class="text-center p-8">
              <h1 class="text-4xl font-bold text-green-600 mb-4">
                <i class="fas fa-hospital mr-3"></i>
                Plataforma Oncológica ACCamargo
              </h1>
              <p class="text-xl text-gray-600 mb-8">Sistema Integrado de Gestão da Jornada Oncológica com IA</p>
              <div class="bg-white rounded-xl shadow-lg p-6 max-w-2xl mx-auto">
                <p class="text-gray-700 mb-4">Acesse a plataforma completa no Cloudflare Pages:</p>
                <a href="https://oncologia-accamargo.pages.dev" class="inline-block bg-green-600 text-white px-8 py-3 rounded-full hover:bg-green-700 transition-colors text-lg font-semibold">
                  <i class="fas fa-external-link-alt mr-2"></i>
                  Acessar Plataforma
                </a>
              </div>
              <div class="mt-8 text-sm text-gray-500">
                <p>Desenvolvido por Jac Fressatto | Geppetto Digital</p>
                <p>© 2025 ACCamargo Cancer Center</p>
              </div>
            </div>
          </body>
          </html>' > dist-pages/index.html
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist-pages'
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4